# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: btyree <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/03 18:30:33 by btyree            #+#    #+#              #
#    Updated: 2019/09/03 18:32:57 by btyree           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRC = display_file.c

all: $(NAME)

$(NAME): 
	@gcc  -Wall -Wextra -Werror -o $(NAME) $(SRC)

clean:
	@/bin/rm -f .*.swp

fclean: clean
	@/bin/rm -f $(NAME)
